// Code generated by mockery v2.43.2. DO NOT EDIT.

package dpkg

import mock "github.com/stretchr/testify/mock"

// MockPackageManagerLinuxDpkg is an autogenerated mock type for the IDpkg type
type MockPackageManagerLinuxDpkg struct {
	mock.Mock
}

type MockPackageManagerLinuxDpkg_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPackageManagerLinuxDpkg) EXPECT() *MockPackageManagerLinuxDpkg_Expecter {
	return &MockPackageManagerLinuxDpkg_Expecter{mock: &_m.Mock}
}

// NewMockPackageManagerLinuxDpkg creates a new instance of MockPackageManagerLinuxDpkg. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPackageManagerLinuxDpkg(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPackageManagerLinuxDpkg {
	mock := &MockPackageManagerLinuxDpkg{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
