with-expecter: True
packages:
  github.com/AmadlaOrg/lay/container:
    interfaces:
      IContainerRuntime:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockContainerRuntime"
          inpackage: True
      IDetector:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockDetector"
          inpackage: True
  github.com/AmadlaOrg/lay/entity:
    interfaces:
      IEntity:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockEntity"
          inpackage: True
  github.com/AmadlaOrg/lay/package_manager:
    interfaces:
      IPackageManager:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockPackageManager"
          inpackage: True
      IDetector:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockDetector"
          inpackage: True
  github.com/AmadlaOrg/lay/binary/compile:
    interfaces:
      IBuildSystem:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockBuildSystem"
          inpackage: True
      IDetector:
        config:
          dir: "{{.InterfaceDir}}"
          mockName: "MockDetector"
          inpackage: True
