// Code generated by mockery v2.43.2. DO NOT EDIT.

package yum

import mock "github.com/stretchr/testify/mock"

// MockPackageManagerLinuxYum is an autogenerated mock type for the IYum type
type MockPackageManagerLinuxYum struct {
	mock.Mock
}

type MockPackageManagerLinuxYum_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPackageManagerLinuxYum) EXPECT() *MockPackageManagerLinuxYum_Expecter {
	return &MockPackageManagerLinuxYum_Expecter{mock: &_m.Mock}
}

// NewMockPackageManagerLinuxYum creates a new instance of MockPackageManagerLinuxYum. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPackageManagerLinuxYum(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPackageManagerLinuxYum {
	mock := &MockPackageManagerLinuxYum{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
