// Code generated by mockery v2.43.2. DO NOT EDIT.

package rpm

import mock "github.com/stretchr/testify/mock"

// MockPackageManagerLinuxRpm is an autogenerated mock type for the IRpm type
type MockPackageManagerLinuxRpm struct {
	mock.Mock
}

type MockPackageManagerLinuxRpm_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPackageManagerLinuxRpm) EXPECT() *MockPackageManagerLinuxRpm_Expecter {
	return &MockPackageManagerLinuxRpm_Expecter{mock: &_m.Mock}
}

// NewMockPackageManagerLinuxRpm creates a new instance of MockPackageManagerLinuxRpm. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPackageManagerLinuxRpm(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPackageManagerLinuxRpm {
	mock := &MockPackageManagerLinuxRpm{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
