// Code generated by mockery v2.43.2. DO NOT EDIT.

package package_manager

import mock "github.com/stretchr/testify/mock"

// MockPackageManager is an autogenerated mock type for the IPackageManager type
type MockPackageManager struct {
	mock.Mock
}

type MockPackageManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPackageManager) EXPECT() *MockPackageManager_Expecter {
	return &MockPackageManager_Expecter{mock: &_m.Mock}
}

// NewMockPackageManager creates a new instance of MockPackageManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPackageManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPackageManager {
	mock := &MockPackageManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
