// Code generated by mockery v2.43.2. DO NOT EDIT.

package apt

import mock "github.com/stretchr/testify/mock"

// MockPackageManagerLinuxApt is an autogenerated mock type for the IApt type
type MockPackageManagerLinuxApt struct {
	mock.Mock
}

type MockPackageManagerLinuxApt_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPackageManagerLinuxApt) EXPECT() *MockPackageManagerLinuxApt_Expecter {
	return &MockPackageManagerLinuxApt_Expecter{mock: &_m.Mock}
}

// NewMockPackageManagerLinuxApt creates a new instance of MockPackageManagerLinuxApt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPackageManagerLinuxApt(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPackageManagerLinuxApt {
	mock := &MockPackageManagerLinuxApt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
