// Code generated by mockery v2.43.2. DO NOT EDIT.

package winget

import mock "github.com/stretchr/testify/mock"

// MockPackageManagerWindowsWinget is an autogenerated mock type for the IWinget type
type MockPackageManagerWindowsWinget struct {
	mock.Mock
}

type MockPackageManagerWindowsWinget_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPackageManagerWindowsWinget) EXPECT() *MockPackageManagerWindowsWinget_Expecter {
	return &MockPackageManagerWindowsWinget_Expecter{mock: &_m.Mock}
}

// NewMockPackageManagerWindowsWinget creates a new instance of MockPackageManagerWindowsWinget. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPackageManagerWindowsWinget(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPackageManagerWindowsWinget {
	mock := &MockPackageManagerWindowsWinget{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
