// Code generated by mockery v2.43.2. DO NOT EDIT.

package dnf

import mock "github.com/stretchr/testify/mock"

// MockPackageManagerLinuxDnf is an autogenerated mock type for the IDnf type
type MockPackageManagerLinuxDnf struct {
	mock.Mock
}

type MockPackageManagerLinuxDnf_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPackageManagerLinuxDnf) EXPECT() *MockPackageManagerLinuxDnf_Expecter {
	return &MockPackageManagerLinuxDnf_Expecter{mock: &_m.Mock}
}

// NewMockPackageManagerLinuxDnf creates a new instance of MockPackageManagerLinuxDnf. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPackageManagerLinuxDnf(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPackageManagerLinuxDnf {
	mock := &MockPackageManagerLinuxDnf{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
