// Code generated by mockery v2.43.2. DO NOT EDIT.

package scoop

import mock "github.com/stretchr/testify/mock"

// MockPackageManagerWindowsScoop is an autogenerated mock type for the IScoop type
type MockPackageManagerWindowsScoop struct {
	mock.Mock
}

type MockPackageManagerWindowsScoop_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPackageManagerWindowsScoop) EXPECT() *MockPackageManagerWindowsScoop_Expecter {
	return &MockPackageManagerWindowsScoop_Expecter{mock: &_m.Mock}
}

// NewMockPackageManagerWindowsScoop creates a new instance of MockPackageManagerWindowsScoop. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPackageManagerWindowsScoop(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPackageManagerWindowsScoop {
	mock := &MockPackageManagerWindowsScoop{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
